# Generated by Django 6.1 on 2026-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='globe_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=50)),
                ('airport_no', models.CharField(max_length=10)),
                ('active_status', models.BooleanField(default=False)),
            ],
        ),
    ]
