# Generated by Django 6.1 on 2026-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globe_employee',
            name='mail',
            field=models.CharField(default='k@gmail.com'),
        ),
        migrations.AddField(
            model_name='globe_employee',
            name='password',
            field=models.CharField(default='smp'),
        ),
    ]
