# Generated by Django 6.1 on 2026-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0002_globe_employee_mail_globe_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globe_employee',
            name='airport_no',
            field=models.CharField(max_length=100),
        ),
    ]
