# Generated by Django 6.1 on 2026-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0003_alter_globe_employee_airport_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEL_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('pass_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=50)),
                ('visa_no', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=60)),
            ],
        ),
    ]
