# Generated by Django 6.1 on 2026-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0004_del_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('pass_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=50)),
                ('visa_no', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CCU_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('pass_name', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=50)),
                ('visa_no', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=60)),
            ],
        ),
    ]
